GO_EASY_ON_ME = 1
export THEOS_DEVICE_IP = localhost

include theos/makefiles/common.mk

TWEAK_NAME = LockAssistant
LockAssistant_FILES = Tweak.x
LockAssistant_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
