GO_EASY_ON_ME = 1
export THEOS_DEVICE_IP = localhost

include theos/makefiles/common.mk

TWEAK_NAME = CamHooks
CamHooks_FILES = Tweak.x
CamHooks_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk

